services:
  api:
    build: .
    container_name: model-training-service
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - ./app:/model_service/app
      - ./models:/model_service/models
      - ./data:/model_service/data
    restart: "no"